version: "3.7"

services:

  nginx:
    image: nginx:1.19.5
    ports:
      - 80:80
    networks:
      - DjangoMyself_network
    volumes:
      - /home/ekdns9665/nginx.conf:/etc/nginx/nginx.conf
      - djangomyself_static:/data/static/
      - djangomyself_media:/data/media/

  django:
    image: djangomyself:v1.5.1
    networks:
      - DjangoMyself_network
    volumes:
      - djangomyself_static:/home/DjangoMyself/staticfiles/
      - djangomyself_media:/home/DjangoMyself/media/
    secrets:
      - DJANGO_SECRET_KEY
      - MARIADB_USER
      - MARIADB_PASSWORD

  mariadb:
    image: mariadb:10.5
    networks:
      - DjangoMyself_network
    volumes:
      - djangomyself_mariadb:/var/lib/mysql
    secrets:
      - MARIADB_ROOT_PASSWORD
      - MARIADB_USER
      - MARIADB_PASSWORD
    environment:
      MARIADB_DATABASE: django
      MARIADB_USER_FILE: /run/secrets/MARIADB_USER
      MARIADB_PASSWORD_FILE: /run/secrets/MARIADB_PASSWORD
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/MARIADB_ROOT_PASSWORD

networks:
  DjangoMyself_network:

volumes:
  djangomyself_static:
  djangomyself_media:
  djangomyself_mariadb:

secrets:
  DJANGO_SECRET_KEY:
    external: true
  MARIADB_ROOT_PASSWORD:
    external: true
  MARIADB_USER:
    external: true
  MARIADB_PASSWORD:
    external: true